
# ----------------------------------------------------------------------------------
#
# Copyright Microsoft Corporation
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------------
. (Join-Path $PSScriptRoot "\..\utils\FlexibleServerUtils.ps1")
$DEFAULT_VNET_PREFIX = '10.0.0.0/16'
$DEFAULT_SUBNET_PREFIX = '10.0.0.0/24'
$DEFAULT_DB_NAME = 'flexibleserverdb'
$DELEGATION_SERVICE_NAME = "Microsoft.DBforMySQL/flexibleServers"
function New-AzMySqlFlexibleServer {
    [OutputType([Microsoft.Azure.PowerShell.Cmdlets.MySql.Models.Api20200701Preview.IServerAutoGenerated])]
    [CmdletBinding(DefaultParameterSetName='CreateExpanded', PositionalBinding=$false, SupportsShouldProcess, ConfirmImpact='Medium')]
    [Microsoft.Azure.PowerShell.Cmdlets.MySql.Description('Creates a new server.')]
    param(
        [Parameter(HelpMessage = 'The name of the server.')]
        [Alias('ServerName')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Path')]
        [System.String]
        ${Name},

        [Parameter(HelpMessage = 'The name of the resource group that contains the resource, You can obtain this value from the Azure Resource Manager API or the portal.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Path')]
        [System.String]
        ${ResourceGroupName},

        [Parameter(HelpMessage='The subscription ID that identifies an Azure subscription.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Path')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Runtime.DefaultInfo(Script='(Get-AzContext).Subscription.Id')]
        [System.String]
        ${SubscriptionId},

        [Parameter(HelpMessage = 'The location the resource resides in.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        [System.String]
        ${Location},

        [Parameter(HelpMessage = 'Administrator username for the server. Once set, it cannot be changed.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        [System.String]
        ${AdministratorUserName},

        [Parameter(HelpMessage = 'The password of the administrator. Minimum 8 characters and maximum 128 characters. Password must contain characters from three of the following categories: English uppercase letters, English lowercase letters, numbers, and non-alphanumeric characters.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        [System.Security.SecureString]
        [ValidateNotNullOrEmpty()]
        ${AdministratorLoginPassword},

        [Parameter(HelpMessage = 'The name of the sku, typically, tier + family + cores, e.g. Standard_B1ms, Standard_D2ds_v4.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        [System.String]
        ${Sku},

        [Parameter(HelpMessage = 'Compute tier of the server. Accepted values: Burstable, GeneralPurpose, Memory Optimized. Default: Burstable.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        [System.String]
        ${SkuTier},

        [Parameter(HelpMessage = "Backup retention days for the server. Day count is between 7 and 35.")]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        [System.Int32]
        ${BackupRetentionDay},

        [Parameter(HelpMessage = 'Max storage allowed for a server.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        [System.Int32]
        ${StorageInMb},

        [Parameter(HelpMessage = 'Application-specific metadata in the form of key-value pairs.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Runtime.Info(PossibleTypes=([Microsoft.Azure.PowerShell.Cmdlets.MySql.Models.Api20171201.IServerForCreateTags]))]
        [System.Collections.Hashtable]
        ${Tag},

        [Parameter(HelpMessage = 'Server version.')]
        [ArgumentCompleter([Microsoft.Azure.PowerShell.Cmdlets.MySql.Support.ServerVersion])]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Support.ServerVersion]
        ${Version},

        [Parameter(HelpMessage = 'The virtual network address prefix.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        ${AddressPrefix},

        [Parameter(HelpMessage = 'The subnet IP address prefix to use when creating a new VNet in CIDR format. Default value is 10.0.0.0/24.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        ${SubnetPrefix},

        [Parameter(HelpMessage = 'Resource ID of an existing subnet. Please note that the subnet will be delegated to Microsoft.DBforPostgreSQL/flexibleServers/Microsoft.DBforMySQL/flexibleServers.After delegation, this subnet cannot be used for any other type of Azure resources.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        ${Subnet},

        [Parameter(HelpMessage = 'The IP address prefix to use when creating a new virtual network in CIDR format. Default value is 10.0.0.0/16.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        ${VnetPrefix},

        [Parameter(HelpMessage = 'Name of an existing virtual network or name of a new one to create. The name must be between 2 to 64 characters. The name must begin with a letter or number, end with a letter, number or underscore, and may contain only letters, numbers, underscores, periods, or hyphens.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        ${Vnet},

        [Parameter(HelpMessage = "
            Determines the public access. Enter single or range of IP addresses to be 
            included in the allowed list of IPs. IP address ranges must be dash-
            separated and not contain any spaces. Specifying 0.0.0.0 allows public
            access from any resources deployed within Azure to access your server.
            Specifying no IP address sets the server in public access mode but does
            not create a firewall rule.")]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        ${PublicAccess},

        [Parameter(HelpMessage = 'Enable or disable high availability feature.  Default value is Disabled. Default: Disabled.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Body')]
        ${HighAvailability},

        [Parameter(HelpMessage = 'The credentials, account, tenant, and subscription used for communication with Azure.')]
        [Alias('AzureRMContext', 'AzureCredential')]
        [ValidateNotNull()]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Azure')]
        [System.Management.Automation.PSObject]
        ${DefaultProfile},

        [Parameter(HelpMessage = 'Run the command as a job.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Runtime')]
        [System.Management.Automation.SwitchParameter]
        ${AsJob},

        [Parameter(DontShow, HelpMessage = 'Wait for .NET debugger to attach.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Runtime')]
        [System.Management.Automation.SwitchParameter]
        ${Break},

        [Parameter(DontShow)]
        [ValidateNotNull()]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Runtime')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Runtime.SendAsyncStep[]]
        # SendAsync Pipeline Steps to be appended to the front of the pipeline.
        ${HttpPipelineAppend},

        [Parameter(DontShow)]
        [ValidateNotNull()]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Runtime')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Runtime.SendAsyncStep[]]
        # SendAsync Pipeline Steps to be prepended to the front of the pipeline.
        ${HttpPipelinePrepend},

        [Parameter(HelpMessage = 'Run the command asynchronously.')]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Runtime')]
        [System.Management.Automation.SwitchParameter]
        ${NoWait},

        [Parameter(DontShow)]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Runtime')]
        [System.Uri]
        # The URI for the proxy server to use.
        ${Proxy},

        [Parameter(DontShow)]
        [ValidateNotNull()]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Runtime')]
        [System.Management.Automation.PSCredential]
        # Credentials for a proxy server to use for the remote call.
        ${ProxyCredential},

        [Parameter(DontShow)]
        [Microsoft.Azure.PowerShell.Cmdlets.MySql.Category('Runtime')]
        [System.Management.Automation.SwitchParameter]
        # Use the default credentials for the proxy.
        ${ProxyUseDefaultCredentials}
    )

    process {
        try {
            if (!$PSBoundParameters.ContainsKey('Location')) {
                $PSBoundParameters.Location = 'westus2'
            }

            if (!$PSBoundParameters.ContainsKey('AdministratorLoginPassword')) {
                $Password = Get-GeneratePassword
                $PSBoundParameters.AdministratorLoginPassword = $Password | ConvertTo-SecureString -AsPlainText -Force
                Write-Host "G Password: " $Password
                Write-Host "Password: " $PSBoundParameters.AdministratorLoginPassword
            }
            $PSBoundParameters.AdministratorLoginPassword = . "$PSScriptRoot/../utils/Unprotect-SecureString.ps1" $PSBoundParameters['AdministratorLoginPassword']

            if(!$PSBoundParameters.ContainsKey('ResourceGroupName')) {
                $PSBoundParameters.ResourceGroupName = Get-RandomNumbers -Prefix 'group' -Length 10
                $Msg = "Creating Resource Group " + $PSBoundParameters.ResourceGroupName + "..."
                Write-Host $Msg
                If (!(Test-Path (Join-Path $PSScriptRoot '../generated/modules/Az.Resources'))){
                    Write-Host "No resources module here"
                    Find-Module -Name Az.Resources -RequiredVersion 2.0.1 -Repository 'PSGallery' | Save-Module -Path (Join-Path $PSScriptRoot '../generated/modules')
                }
                Else {
                    Write-Host "Yes resources module here"
                }
                Import-Module -Name Az.Resources -RequiredVersion 2.0.1
                New-AzResourceGroup -Name $PSBoundParameters.ResourceGroupName -Location $PSBoundParameters.Location
            }

            if ($PSBoundParameters.ContainsKey('Name')) {
                $Request = [Microsoft.Azure.PowerShell.Cmdlets.MySql.Models.Api20171201.NameAvailabilityRequest]::new()
                $Request.name = $PSBoundParameters['Name']
                $Request.type = 'Microsoft.DBforMySQL/flexibleServers'
                $AvailabilityResult = Test-AzMySqlFlexibleServerNameAvailability -NameAvailabilityRequest $Request
                if (!$AvailabilityResult.NameAvailable) {
                    $Msg = "The server name " + $PSBoundParameters['Name'] + " already exists. Please re-run command with some other server name."
                    Write-Error $Msg
                }
                $PSBoundParameters.ServerName = $PSBoundParameters['Name']
                $null = $PSBoundParameters.Remove('Name')
            }
            else {
                $PSBoundParameters.ServerName = Get-RandomNumbers -Prefix 'server' -Length 10
                $Msg = "Provisioning server " + $PSBoundParameters.ServerName
                Write-Host $Msg
            }

            if ($PSBoundParameters.ContainsKey('Sku')) {
                $PSBoundParameters.SkuName = $PSBoundParameters['Sku']
                $null = $PSBoundParameters.Remove('Sku')
            }
            else {
                $PSBoundParameters.SkuName = 'Standard_B1ms'
            }

            if ($PSBoundParameters.ContainsKey('BackupRetentionDay')) {
                $PSBoundParameters.StorageProfileBackupRetentionDay = $PSBoundParameters['BackupRetentionDay']
                $null = $PSBoundParameters.Remove('BackupRetentionDay')
            }
            else {
                $PSBoundParameters.StorageProfileBackupRetentionDay = 7
            }

            if ($PSBoundParameters.ContainsKey('StorageInMb')) {
                $PSBoundParameters.StorageProfileStorageMb = $PSBoundParameters['StorageInMb']
                $null = $PSBoundParameters.Remove('StorageInMb')
            }
            else {
                $PSBoundParameters.StorageProfileStorageMb = 10240
            }

            if (!$PSBoundParameters.ContainsKey('Version')) {
                $PSBoundParameters.Version = '5.7'
            }

            if (!$PSBoundParameters.ContainsKey('SkuTier')) {
                $PSBoundParameters.SkuTier = 'Burstable'
            }

            if ($PSBoundParameters.ContainsKey('AdministratorUserName')) {
                $PSBoundParameters.AdministratorLogin = $PSBoundParameters['AdministratorUserName']
                $null = $PSBoundParameters.Remove('AdministratorUserName')
            }
            else {
                $PSBoundParameters.AdministratorLogin = Get-RandomName
            }
            
            $PSBoundParameters.CreateMode = [Microsoft.Azure.PowerShell.Cmdlets.MySql.Support.CreateMode]::Default

            $NetworkKeys = 'PublicAccess', 'Subnet', 'Vnet', 'SubnetPrefix', 'VnetPrefix'
            $NetworkParameters = @{}
            ForEach($Key in $NetworkKeys){
                If ($PSBoundParameters.ContainsKey($Key)){ 
                    $NetworkParameters[$Key] = $PSBoundParameters[$Key]
                    $null = $PSBoundParameters.Remove($Key)
                }
            }
            $RequiredKeys = 'SubscriptionId', 'ResourceGroupName', 'ServerName', 'Location'
            ForEach($Key in $RequiredKeys){ $NetworkParameters[$Key] = $PSBoundParameters[$Key] }

            $SubnetId = CreateNetworkResource $NetworkParameters | Out-String
            $PSBoundParameters.DelegatedSubnetArgumentSubnetArmResourceId = $SubnetId.Trim()
            If ([string]::IsNullOrEmpty($PSBoundParameters.DelegatedSubnetArgumentSubnetArmResourceId)) {
                $null = $PSBoundParameters.Remove('DelegatedSubnetArgumentSubnetArmResourceId')
            }

            Az.MySql.internal\New-AzMySqlFlexibleServer @PSBoundParameters
            New-AzMySqlFlexibleServerDatabase -Name $DEFAULT_DB_NAME -ResourceGroupName $PSBoundParameters.ResourceGroupName -ServerName $PSBoundParameters.ServerName -Charset utf8
            CreateFirewallRule $NetworkParameters

        } catch {
            throw
        }
    }
}
function CreateNetworkResource($Parameters) {
    [OutputType([string])]
    $WarningPreference = 'silentlycontinue'
    $SubnetId = $null
    If (!(Test-Path (Join-Path $PSScriptRoot '../generated/modules/Az.Network'))){
        Find-Module -Name Az.Network -RequiredVersion 3.0.0 -Repository 'PSGallery' | Save-Module -Path (Join-Path $PSScriptRoot '../generated/modules')
    }
    Import-Module -Name Az.Network -RequiredVersion 3.0.0

    # 1. Error Handling
    # Raise error when user passes values for both parameters
    if ($Parameters.ContainsKey('Subnet') -And $Parameters.ContainsKey('PublicAccess')) {
        Write-Error "Incorrect usage : A combination of the parameters --subnet and --public_access is invalid. Use either one of them."
    }

    # When address space parameters are passed, the only valid combination is : --vnet, --subnet, --vnet-address-prefix, --subnet-address-prefix
    if ($Parameters.ContainsKey('Vnet') -Or $Parameters.ContainsKey('Subnet')) {
        if (($Parameters.ContainsKey('VnetPrefix') -And !$Parameters.ContainsKey('SubnetPrefix')) -Or
            (!$Parameters.ContainsKey('VnetPrefix') -And $Parameters.ContainsKey('SubnetPrefix')) -Or 
            ($Parameters.ContainsKey('VnetPrefix') -And $Parameters.ContainsKey('SubnetPrefix') -And (!$Parameters.ContainsKey('Vnet') -Or !$Parameters.ContainsKey('Subnet')))){
                Write-Error "Incorrect usage : --vnet, --subnet, --vnet-address-prefix, --subnet-address-prefix must be supplied together."
        }
    }
    
    #Handle Vnet scenario
    If ($Parameters.ContainsKey('Vnet') -Or $Parameters.ContainsKey('Subnet')) {
        # Only the Subnet ID provided.. 
        If (!$Parameters.ContainsKey('Vnet') -And $Parameters.ContainsKey('Subnet')) {
            If (IsValidResourceId $Parameters.ContainsKey('Subnet')){
                Try { # Valid Subnet ID is provided
                    $Subnet = Get-AzVirtualNetworkSubnetConfig -ResourceId $Parameters.Subnet -ErrorAction Stop
                    Try { # Valid and delegated
                        $Delegations = Get-AzDelegation -Subnet $Subnet 
                        $Delegations | ForEach-Object {If ($PSItem.ServiceName -ne $DELEGATION_SERVICE_NAME) {
                            $Msg = "Can not use subnet with existing delegations other than " + $DELEGATION_SERVICE_NAME
                            Write-Error $Msg
                        }}
                    } Catch { # Valid but incorrect delegation
                        $null = $Subnet = Get-AzVirtualNetworkSubnetConfig -ResourceId $Parameters.Subnet
                        $null = $Subnet = Add-AzDelegation -Name $DELEGATION_SERVICE_NAME -ServiceName $DELEGATION_SERVICE_NAME -Subnet $Subnet
                    }
                }
                Catch { # Invalid subnet ID is provided, creating a new one. 
                    $Splits = $Parameters.ContainsKey('Subnet') -split "/"
                    $Parameters.VnetName = $Splits[8]
                    $Parameters.SubnetName = $Splits[10]
                    CreateVnetSubnet @Parameters
                }
            }
            Else {
                Write-Error "The Subnet ID is not a valid form of resource id."
            }
        }
        ElseIf ($Parameters.ContainsKey('Vnet') -And !$Parameters.ContainsKey('Subnet')) {
            $Splits = $Parameters.Vnet -split "/"
            If (IsValidResourceId $Parameters.ContainsKey('Vnet')){
                Write-Host "You have supplied a Vnet Id. Verifying its existence..."
                IsValidRgLocation @Parameters
                $Subnet = CreateVnetSubnet @Parameters
            }
            ElseIf ($Splits.length -eq 1) {
                Write-Host "You have supplied a Vnet Name. Verifying its existence..."
                $Subnet = CreateVnetSubnet @Parameters
                $ParsedSubnetId = ParseResourceId $Subnet.Id
                IsValidRgLocation $ParsedSubnetId $Parameters 
            }
            Else {
                Write-Error "Incorrectly formed Vnet id or Vnet name"
            }
        }
        ElseIf ($Parameters.ContainsKey('Vnet') -And $Parameters.ContainsKey('Subnet') -And $Parameters.ContainsKey('SubnetPrefix') -And $Parameters.ContainsKey('VnetPrefix')) {
            $VnetSplits = $Parameters.Vnet -split "/"
            $SubnetSplits = $Parameters.Subnet -split "/"
            If ($VnetSplits.length -eq 1 -And $SubnetSplits -eq 1) {
                $Subnet = CreateVnetSubnet @Parameters
            }
            Else {
                Write-Error "If you pass an address prefix, please consider passing a name (instead of Id) for a subnet or vnet."
            }
        }
        ElseIf ($Parameters.ContainsKey('Vnet') -And $Parameters.ContainsKey('Subnet')) {
            If ($VnetSplits.length -eq 1 -And $SubnetSplits -eq 1) {
                $Subnet = CreateVnetSubnet @Parameters
            }
            Else {
                Write-Error "If you pass both --vnet and --subnet, consider passing names instead of ids."
            }
        }
    }

    ElseIf (!$Parameters.ContainsKey('PublicAccess') -And !$Parameters.ContainsKey('Subnet') -And !$Parameters.ContainsKey('Vnet')) {
        $VnetName = 'VNET' + $Parameters.ServerName
        $SubnetName = 'Subnet' + $Parameters.ServerName
        $VnetAddrPrefix = $DEFAULT_VNET_PREFIX
        $SubnetAddrPrefix = $DEFAULT_SUBNET_PREFIX

        $Msg = 'Creating new vnet' + $VnetName + 'in resource group' + $Parameters.ResourceGroupName
        $Subnet = New-AzVirtualNetworkSubnetConfig -Name $SubnetName -AddressPrefix $SubnetAddrPrefix
        New-AzVirtualNetwork -Name $VnetName -ResourceGroupName $Parameters.ResourceGroupName -Location $Parameters.Location -AddressPrefix $VnetAddrPrefix -Subnet $Subnet

        $null = $Vnet = Get-AzVirtualNetwork -Name $VnetName -ResourceGroupName $Parameters.ResourceGroupName
        $null = $Subnet = Get-AzVirtualNetworkSubnetConfig -Name $SubnetName -VirtualNetwork $Vnet
        $null = $Subnet = Add-AzDelegation -Name $DELEGATION_SERVICE_NAME -ServiceName $DELEGATION_SERVICE_NAME -Subnet $Subnet
        $null = Set-AzVirtualNetwork -VirtualNetwork $Vnet
        
        $Subnet = Get-AzVirtualNetwork -Name $VnetName -ResourceGroupName $Parameters.ResourceGroupName | Get-AzVirtualNetworkSubnetConfig -Name $SubnetName

        $Msg = 'Creating new subnet' + $SubnetName + 'in resource group ' + $Parameters.ResourceGroupName + 'and delegating it to ' + $DELEGATION_SERVICE_NAME
        Write-Host $Msg

        $SubnetId = $Subnet.Id
    }  

    return $SubnetId
}
function CreateVnetSubnet($Parameters){
    Try {
        $Vnet = Get-AzVirtualNetwork -Name $Parameters.VnetName -ResourceGroupName $Parameters.ResourceGroupName
    }
    Catch {
        $Msg = "The Vnet does not exist. Creating new vnet " + $Parameters.VnetName + " in resource group " + $Parameters.ResourceGroupName
        Write-Host $Msg
        If ($Parameters.ContainsKey('SubnetPrefix')){$SubnetAddrPrefix = $Parameters.SubnetPrefix}
        Else {$SubnetAddrPrefix = $DEFAULT_SUBNET_PREFIX}
        If ($Parameters.ContainsKey('VnetPrefix')){$SubnetAddrPrefix = $Parameters.VnetPrefix}
        Else {$VnetAddrPrefix = $DEFAULT_VNET_PREFIX}

        $Subnet = New-AzVirtualNetworkSubnetConfig -Name $SubnetName -AddressPrefix $SubnetAddrPrefix
        New-AzVirtualNetwork -Name $VnetName -ResourceGroupName $Parameters.ResourceGroupName -Location $Parameters.Location -AddressPrefix $VnetAddrPrefix -Subnet $Subnet

        $null = $Vnet = Get-AzVirtualNetwork -Name $VnetName -ResourceGroupName $Parameters.ResourceGroupName
        $null = $Subnet = Get-AzVirtualNetworkSubnetConfig -Name $SubnetName -VirtualNetwork $Vnet
        $null = $Subnet = Add-AzDelegation -Name $DELEGATION_SERVICE_NAME -ServiceName $DELEGATION_SERVICE_NAME -Subnet $Subnet
        $null = Set-AzVirtualNetwork -VirtualNetwork $Vnet

        Return $Subnet.Id
    }

}
function CreateFirewallRule($Parameters) {
     # # Adding firewall rule
     If ($Parameters.ContainsKey('PublicAccess') -And $Parameters.PublicAccess.ToLower() -ne 'none') {
        $Date = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
        If ($Parameters.PublicAccess.ToLower() -eq 'all'){
            $StartIp = '0.0.0.0' 
            $EndIp = '255.255.255.255'
            $RuleName = "AllowAll_" + $Date 
            $FirewallRule = New-AzMySqlFlexibleServerFirewallRule -Name $RuleName -ResourceGroupName $Parameters.ResourceGroupName -ServerName $Parameters.ServerName -EndIPAddress $EndIp -StartIPAddress $StartIp
        }
        Else {
            try{
                $Parsed = $Parameters.PublicAccess -split "-"
                If ($Parsed.length -eq 1) {
                    $StartIp = $Parsed[0]
                    $EndIp = $Parsed[0]
                }
                ElseIf ($Parsed.length -eq 2) {
                    $StartIp = $Parsed[0]
                    $EndIp = $Parsed[1]
                }
                Else { Write-Error "incorrect usage: --public-access. Acceptable values are \'all\', \'none\',\'<startIP>\' and \'<startIP>-<destinationIP>\' where startIP and destinationIP ranges from 0.0.0.0 to 255.255.255.255" }
                
                If ($StartIp -eq '0.0.0.0' -And $EndIp -eq '0.0.0.0') {
                    $RuleName = "AllowAllAzureServicesAndResourcesWithinAzureIps_" + $Date
                }
                Else {
                    $RuleName = "FirewallIPAddress_" + $Date
                }
                $FirewallRule = New-AzMySqlFlexibleServerFirewallRule -Name $RuleName -ResourceGroupName $Parameters.ResourceGroupName -ServerName $Parameters.ServerName -EndIPAddress $EndIp -StartIPAddress $StartIp
            } catch {
                Write-Error "incorrect usage: --public-access. Acceptable values are \'all\', \'none\',\'<startIP>\' and \'<startIP>-<destinationIP>\' where startIP and destinationIP ranges from 0.0.0.0 to 255.255.255.255"
            }
        }
    }
}
function IsValidVnetId($Rid){
    $VnetFormat = "\/subscriptions\/[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}\/resourceGroups\/[-\w\._\(\)]+\/providers\/Microsoft.Network\/VirtualNetworks\/[^<>%&:\\?/]{1,260}$"
    If ( $Rid -match $VnetFormat ) {
        return $True
    }
    return $False
}
function IsValidSubnetId($Rid){
    $SubnetFormat = "\/subscriptions\/[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}\/resourceGroups/[-\w\._\(\)]+\/providers\/Microsoft.Network\/VirtualNetworks\/[^<>%&:\\?/]{1,260}\/subnets\/[^<>%&:\\?/]{1,260}$"
    IF ( $Rid -match $SubnetFormat ) {
        return $True
    }
    return $False
}

function ParseResourceId($Rid){
    $Splits = $Rid -split "/"
    $ParsedResults = @{}
    $ParsedResults["SubscriptionId"] = $Splits[2]
    $ParsedResults["ResourceGroupName"] = $Splits[4]
    $ParsedResults["VnetName"] = $Splits[8]
    If ($Splits.length -eq 10) {
        $ParsedResults["SubnetName"] = $Splits[10]
    }

    return $ParsedResults
}

function IsValidRgLocation($ParsedResults, $Parameters){
    $Group = Get-AzResourceGroup $ParsedResults["ResourceGroupName"]
    $ParsedResults["ocatioin"] = $Group.Location

    If ($Parameters.SubscriptionId -eq $ParsedResults.SubscriptionId -And $Parameters.Location -eq $ParsedResults.Location) {
        Return $True
    }
    Return $False
}

function IsValidARMName($Name){
    $ARM_NAME = '^[^<>%&:\\?/]{1,260}$'
    return $Name -match $ARM_NAME
}